/* Auto-generated cross-language test vectors for tile-cuda */
/* DO NOT EDIT — generated by validate_all.py from test-vectors.json */

#include <cassert>
#include <cstdio>
#include <cstdint>
#include <cstring>
#include <cmath>

static const char* ACTIONS[4] = {"north", "east", "south", "west"};

static void hex_decode(const char* hex, uint8_t* out, size_t len) {
    for (size_t i = 0; i < len; i++) {
        unsigned int b; sscanf(hex + 2*i, "%2x", &b);
        out[i] = (uint8_t)b;
    }
}

int main(void) {
    int pass = 0, fail = 0;

    /* Score encoding (float32 LE) — validates host-side encoding */
    {
        float scores[4] = {0.5f, 0.0f, 0.0f, 0.0f};
        uint8_t expected[16];
        hex_decode("0000003f000000000000000000000000", expected, 16);
        if (memcmp(scores, expected, sizeof(expected)) == 0) {
            pass++;
        } else {
            printf("FAIL v0 score encoding\n");
            fail++;
        }
    }
    {
        float scores[4] = {0.2f, 1.0f, 0.3f, 0.0f};
        uint8_t expected[16];
        hex_decode("cdcc4c3e0000803f9a99993e00000000", expected, 16);
        if (memcmp(scores, expected, sizeof(expected)) == 0) {
            pass++;
        } else {
            printf("FAIL v1 score encoding\n");
            fail++;
        }
    }
    {
        float scores[4] = {0.5f, 0.5f, 0.5f, 0.5f};
        uint8_t expected[16];
        hex_decode("0000003f0000003f0000003f0000003f", expected, 16);
        if (memcmp(scores, expected, sizeof(expected)) == 0) {
            pass++;
        } else {
            printf("FAIL v2 score encoding\n");
            fail++;
        }
    }
    {
        float scores[4] = {0.75f, 3.14159f, 0.0f, 0.9f};
        uint8_t expected[16];
        hex_decode("0000403fd00f4940000000006666663f", expected, 16);
        if (memcmp(scores, expected, sizeof(expected)) == 0) {
            pass++;
        } else {
            printf("FAIL v3 score encoding\n");
            fail++;
        }
    }
    {
        float scores[4] = {0.0f, 0.0f, 0.0f, 0.0f};
        uint8_t expected[16];
        hex_decode("00000000000000000000000000000000", expected, 16);
        if (memcmp(scores, expected, sizeof(expected)) == 0) {
            pass++;
        } else {
            printf("FAIL v4 score encoding\n");
            fail++;
        }
    }
    {
        float scores[4] = {1.0001f, -1.0001f, 0.0f, 0.50000006f};
        uint8_t expected[16];
        hex_decode("4703803f470380bf000000000100003f", expected, 16);
        if (memcmp(scores, expected, sizeof(expected)) == 0) {
            pass++;
        } else {
            printf("FAIL v5 score encoding\n");
            fail++;
        }
    }
    {
        float scores[4] = {0.0f, 0.0f, 0.0f, 1.0f};
        uint8_t expected[16];
        hex_decode("0000000000000000000000000000803f", expected, 16);
        if (memcmp(scores, expected, sizeof(expected)) == 0) {
            pass++;
        } else {
            printf("FAIL v6 score encoding\n");
            fail++;
        }
    }
    {
        float scores[4] = {9.8f, 1.0f, 0.0f, 0.0f};
        uint8_t expected[16];
        hex_decode("cdcc1c410000803f0000000000000000", expected, 16);
        if (memcmp(scores, expected, sizeof(expected)) == 0) {
            pass++;
        } else {
            printf("FAIL v7 score encoding\n");
            fail++;
        }
    }
    {
        float scores[4] = {0.1f, 0.1f, 1.0f, 0.1f};
        uint8_t expected[16];
        hex_decode("cdcccc3dcdcccc3d0000803fcdcccc3d", expected, 16);
        if (memcmp(scores, expected, sizeof(expected)) == 0) {
            pass++;
        } else {
            printf("FAIL v8 score encoding\n");
            fail++;
        }
    }
    {
        float scores[4] = {0.0f, 0.0f, 0.0f, 0.0f};
        uint8_t expected[16];
        hex_decode("00000000000000000000000000000000", expected, 16);
        if (memcmp(scores, expected, sizeof(expected)) == 0) {
            pass++;
        } else {
            printf("FAIL v9 score encoding\n");
            fail++;
        }
    }

    /* Best action tests */
    {
        float scores[4] = {0.5f, 0.0f, 0.0f, 0.0f};
        float max_s = scores[0];
        for (int i = 1; i < 4; i++) if (scores[i] > max_s) max_s = scores[i];
        int best = -1;
        for (int i = 0; i < 4; i++) if (scores[i] == max_s && best == -1) best = i;
        if (best == 0) { pass++; } else { printf("FAIL v0 best action: expected 0 got %d\n", best); fail++; }
    }
    {
        float scores[4] = {0.2f, 1.0f, 0.3f, 0.0f};
        float max_s = scores[0];
        for (int i = 1; i < 4; i++) if (scores[i] > max_s) max_s = scores[i];
        int best = -1;
        for (int i = 0; i < 4; i++) if (scores[i] == max_s && best == -1) best = i;
        if (best == 1) { pass++; } else { printf("FAIL v1 best action: expected 1 got %d\n", best); fail++; }
    }
    {
        float scores[4] = {0.5f, 0.5f, 0.5f, 0.5f};
        float max_s = scores[0];
        for (int i = 1; i < 4; i++) if (scores[i] > max_s) max_s = scores[i];
        int count = 0;
        for (int i = 0; i < 4; i++) if (scores[i] == max_s) count++;
        if (count > 1) { pass++; } else { printf("FAIL v2 best action (expected tie)\n"); fail++; }
    }
    {
        float scores[4] = {0.75f, 3.14159f, 0.0f, 0.9f};
        float max_s = scores[0];
        for (int i = 1; i < 4; i++) if (scores[i] > max_s) max_s = scores[i];
        int best = -1;
        for (int i = 0; i < 4; i++) if (scores[i] == max_s && best == -1) best = i;
        if (best == 1) { pass++; } else { printf("FAIL v3 best action: expected 1 got %d\n", best); fail++; }
    }
    {
        float scores[4] = {0.0f, 0.0f, 0.0f, 0.0f};
        float max_s = scores[0];
        for (int i = 1; i < 4; i++) if (scores[i] > max_s) max_s = scores[i];
        int count = 0;
        for (int i = 0; i < 4; i++) if (scores[i] == max_s) count++;
        if (count > 1) { pass++; } else { printf("FAIL v4 best action (expected tie)\n"); fail++; }
    }
    {
        float scores[4] = {1.0001f, -1.0001f, 0.0f, 0.50000006f};
        float max_s = scores[0];
        for (int i = 1; i < 4; i++) if (scores[i] > max_s) max_s = scores[i];
        int best = -1;
        for (int i = 0; i < 4; i++) if (scores[i] == max_s && best == -1) best = i;
        if (best == 0) { pass++; } else { printf("FAIL v5 best action: expected 0 got %d\n", best); fail++; }
    }
    {
        float scores[4] = {0.0f, 0.0f, 0.0f, 1.0f};
        float max_s = scores[0];
        for (int i = 1; i < 4; i++) if (scores[i] > max_s) max_s = scores[i];
        int best = -1;
        for (int i = 0; i < 4; i++) if (scores[i] == max_s && best == -1) best = i;
        if (best == 3) { pass++; } else { printf("FAIL v6 best action: expected 3 got %d\n", best); fail++; }
    }
    {
        float scores[4] = {9.8f, 1.0f, 0.0f, 0.0f};
        float max_s = scores[0];
        for (int i = 1; i < 4; i++) if (scores[i] > max_s) max_s = scores[i];
        int best = -1;
        for (int i = 0; i < 4; i++) if (scores[i] == max_s && best == -1) best = i;
        if (best == 0) { pass++; } else { printf("FAIL v7 best action: expected 0 got %d\n", best); fail++; }
    }
    {
        float scores[4] = {0.1f, 0.1f, 1.0f, 0.1f};
        float max_s = scores[0];
        for (int i = 1; i < 4; i++) if (scores[i] > max_s) max_s = scores[i];
        int best = -1;
        for (int i = 0; i < 4; i++) if (scores[i] == max_s && best == -1) best = i;
        if (best == 2) { pass++; } else { printf("FAIL v8 best action: expected 2 got %d\n", best); fail++; }
    }
    {
        float scores[4] = {0.0f, 0.0f, 0.0f, 0.0f};
        float max_s = scores[0];
        for (int i = 1; i < 4; i++) if (scores[i] > max_s) max_s = scores[i];
        int count = 0;
        for (int i = 0; i < 4; i++) if (scores[i] == max_s) count++;
        if (count > 1) { pass++; } else { printf("FAIL v9 best action (expected tie)\n"); fail++; }
    }

    /* Wire format test */
    {
        uint32_t n_actions = 4;
        uint32_t entry_size = 16 + 8 * n_actions + 4;
        uint32_t entry_padded = (entry_size + 7) / 8 * 8;
        if (entry_padded == 56) { pass++; } else { printf("FAIL wire entry\n"); fail++; }
        uint32_t total = (64 + entry_padded + 255) / 256 * 256;
        if (total == 256) { pass++; } else { printf("FAIL wire total\n"); fail++; }
    }

    printf("CUDA validation: %d passed, %d failed\n", pass, fail);
    return fail > 0 ? 1 : 0;
}
